\" Definim com volem les equacions a on les volem
.EQ
delim @$
.EN

.PS
down
ellipse "inici de" "principal"
arrow
box "Definim" "senyals"
arrow
box "Escrivim el" "pid"
arrow
box "Esperem la" "senyal"
arrow
box "Diu que llegeix" "Llegeix els pids"
arrow
box "Diu i activa" "segons, minuts i hores"
arrow
box "Inicialitza variables" "de temps"
arrow
box "Espera nova" "senyal"
arc
line 0.125
arc
arc ->
.PE

Al final sembla ser que no cal...
Ja que tampoc ajuda a entendre el mateix programa
